#!/usr/bin/env bash

STYLE=$(git config --get hooks.clangformat.style)

if [ -n "${STYLE}" ] ; then
 STYLEARG="-style=${STYLE}"
else
 STYLEARG="-style=file"
fi

format_file() {
 file="${1}"
 clang-format ${STYLEARG} ${1} -sort-includes -output-replacements-xml | grep "<replacement " >/dev/null
 if [ $? -ne 1 ]
 then
   echo "File ["${1}"] in commit did not match format rules"
   exit 1;
 fi
}

case "${1}" in
 --about )
   echo "Runs clang-format on source files"
   ;;
 * )
   for file in `git diff --cached --name-only --diff-filter=ACMRT | grep -E "^(.*\.(c|cpp|h|hpp)\$)"` ; do
     format_file "${file}"
   done
   ;;
esac
